site_name: Quantum Computing

extra_javascript:
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni

theme:
  name: 'material'
  highlightjs: true
  hljs_languages: [python]
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true

extra_css:
  - extra.css

extra:
  analytics:
    provider: google
    property: UA-156178967-1





nav:
- Home: index.md
- Introduction to Quantum Computing: introduction_to_quantum_computing.md
- Basic Quantum Mechanics: basic_quantum_mechanics.md
- Quantum States and Qubits: quantum_states_and_qubits.md
- Quantum Entanglement: quantum_entanglement.md
- Quantum Superposition: quantum_superposition.md
- Introduction to Quantum Algorithms: introduction_to_quantum_algorithms.md
- Shor's Algorithm: shors_algorithm.md
- Grover's Algorithm: grovers_algorithm.md
- Quantum Fourier Transform: quantum_fourier_transform.md
- Quantum Simulation: quantum_simulation.md
- Quantum Machine Learning: quantum_machine_learning.md
- Quantum Annealing: quantum_annealing.md
- Variational Quantum Eigensolver: variational_quantum_eigensolver.md
- Quantum Approximate Optimization Algorithm (QAOA): quantum_approximate_optimization_algorithm.md
- Quantum Phase Estimation: quantum_phase_estimation.md
- Amplitude Amplification: amplitude_amplification.md
- Quantum Walks: quantum_walks.md
- Quantum Neural Networks: quantum_neural_networks.md
- Quantum Support Vector Machines: quantum_support_vector_machines.md
- Quantum Generative Adversarial Networks: quantum_generative_adversarial_networks.md
- Quantum Boltzmann Machines: quantum_boltzmann_machines.md
- Quantum Clustering Algorithms: quantum_clustering_algorithms.md
- Quantum Principal Component Analysis: quantum_principal_component_analysis.md
- Quantum Gate Model: quantum_gate_model.md
- Quantum Circuit Model: quantum_circuit_model.md
- Adiabatic Quantum Computing: adiabatic_quantum_computing.md
- Topological Quantum Computing: topological_quantum_computing.md
- Quantum Information Theory: quantum_information_theory.md
- Quantum Cryptography: quantum_cryptography.md
- Quantum Error Correction: quantum_error_correction.md
- Quantum Entropy: quantum_entropy.md
- Quantum Computing Applications: quantum_computing_applications.md
- Quantum Communication: quantum_communication.md
- Quantum Sensing: quantum_sensing.md
- Quantum Metrology: quantum_metrology.md
- Quantum Programming Languages: quantum_programming_languages.md
- Quantum Software Frameworks: quantum_software_frameworks.md
- Quantum Simulators: quantum_simulators.md
- Quantum Cloud Computing: quantum_cloud_computing.md
- Quantum Development Kits: quantum_development_kits.md
